version: "3"
services:
  scrapers:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MR_PROXY_WEBSITE=https://proxy.mainrest.ru
      - AGENT_RESPONSE_TIMEOUT=30000
      - AGENT_BROWSER_TIMEOUT=1000
      - AGENT_BROWSER_TIMES=32
      - AGENT_PROXY_SERVER=